### PR TITLE
Dialog & all its inherited widget added

### LINKED ISSUE #108: Nested window support (Modals or Dialogs)
**Describe the bug**
Opening and closing new windows doesn't work properly when nested inside another window

**To Reproduce**
Run the following example code
````tsx
import React, { useState } from "react";
import { Renderer, Window, View, Button, Text } from "@nodegui/react-nodegui";

function MainWindow() {
  const [open1, setOpen1] = useState(false);
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);

  return (
    <>
      <Window windowTitle="Main window">
        <View>
          <Button text="Nested in view"   on={{clicked: () => setOpen1(!open1)}}/>
          <Button text="Nested in window" on={{clicked: () => setOpen2(!open2)}}/>
          <Button text="Not nested"       on={{clicked: () => setOpen3(!open3)}}/>
          {open1 && <Dialog text="Nested in view"/>}{/* Does not work */}
        </View>
        {open2 && <Dialog text="Nested in window"/>}{/* Partialy working */}
      </Window>
      {open3 && <Dialog text="Not nested"/>}{/* This works */}
    </>
  );
}

function Dialog({text}: {text: string}) {
  return (
    <Window windowTitle={text}>
      <View>
        <Text>{text}</Text>
      </View>
    </Window>
  )
}

Renderer.render(<MainWindow />);
````

**Expected behavior**
That windows can be open and closed no matter where they are placed in the react tree.

**Desktop (please complete the following information):**
 - OS: Linux
 - NodeGUI version: 0.12.1
 - React NodeGUI version: 0.4.0 
 - OS Version: Arch Linux

### PR DESCRIPTION
**Pull request by KRTirtho**
Fixes #108
Added Components:
- Dialog
- ColorDialog
- FileDialog
- FontDialog
- InputDialog
- ProgressDialog

Edited/Modified:
- View (both were edited to add compatibility & support for all `NodeDialog` inherited widgets)
- BoxView

**Disclaimer!**: `Dialog` & its all inherited widgets can only be used inside a `View` or `BoxView`. Using it in other places will not work. It'd cause the Dialog components to not appear. This behavior was expected since adding `NodeDialog` inherited widgets to Layout or as a child to other widgets doesn't work. Thus filters were added to `View` & `BoxView` to not let any `instance` of `NodeDialog` to be added in the layout tree

An working example:
```tsx
import React, {useState} from "react";
import { Text, Renderer, Window, View, Button, Dialog } from "@nodegui/react-nodegui";

const App = () => {
  const [open, setOpen] = useState(false);

  return (
    <Window styleSheet={styleSheet}>
      <View id="container">
        <Dialog open={open}/>
        <Button text="Click me" on={{clicked:()=>setOpen(!open)}}></Button>
      </View>
    </Window>
  );
};

const styleSheet = `
  #container {
    flex: 1;
    min-height: '100%';
    justify-content: 'center';
  }
`;

Renderer.render(<App />);
```

Thanks @a7ul

### CODE REVIEW

**Comment by a7ul** [comment]
Amazing work!!!

```
Dialog & its all inherited widgets can only be used inside a View or BoxView. Using it in other places will not work. It'd cause the Dialog components to not appear. 
```
Can you add a warning log here saying child wasnt rendered because it was used not inside a view or boxview when this happens ?

**Review by a7ul — APPROVED** [review]

**Comment by KRTirtho** [comment]
Currently I don't know any way of accessing parent Component/Widget in react thus determining whether any component was added as a child to a certain type of Component/s isn't possible in that view. But if there's any `method/property` of `QDialog` that can get the instance of parent widget or anything about parent widget please let me know...

**Comment by a7ul** [comment]
You can take a look at this: https://github.com/nodegui/react-nodegui/blob/master/src/components/TabItem/RNTabItem.ts

But If its too complex for this use case we can go ahead with too.

**Comment by KRTirtho** [comment]
Well, I looked into that example.. But I've to extend `QDialog` to inherit the functionalities but looks like `TabItem` isn't a nodegui/qt widget. It is a vanilla widget & was fundamentally created for react-nodegui's `Tabs` so inheriting `Component` was possible. 
If you really want to show a warning log about adding a `NodeDialog` instance to the layout tree than you can do so in nodegui's `widget.layout.addWidget`, `widget.setWidget` or `widget.setCentralWidget`. It'd even make it better for the nodegui's part too preventing accidental addition of Dialog as child

**Comment by a7ul** [comment]
@all-contributors add @KRTirtho  for code

**Pull request merged**
