### PR TITLE
Implements QSlider

### PR DESCRIPTION
**Pull request by matrunchyk**
Part of https://github.com/nodegui/react-nodegui/issues/140

### CODE REVIEW

**Comment by matrunchyk** [comment]
Depends on https://github.com/nodegui/react-nodegui/pull/136

**Comment by master-atul** [comment]
hi I can take a look at these in the evening

**Comment by matrunchyk** [comment]
Cool, thanks

**Comment by matrunchyk** [comment]
Thank you! 👍

**Comment by master-atul** [comment]
@all-contributors add @matrunchyk  for code

**Pull request merged**
