### PR TITLE
upgrade module to work with latest nodegui (0.57.1)

### PR DESCRIPTION
**Pull request by KaMeHb-UA**
\+ docs =)

P.S. I hadn't enough time to test all the stuff properly so there may be some small issues

### CODE REVIEW

**Comment by KaMeHb-UA** [comment]
tested a bit, there is issues with layout, temporary marking this PR as draft

**Comment by KaMeHb-UA** [comment]
fixed basic issues, sample app operates normally but there is still need to check if all the stuff's working well by someone else

**Review by a7ul — APPROVED** [review]
Tested this and it looks amazing.
Thanks for the great work

**Comment by a7ul** [comment]
@allcontributors add @KaMeHb-UA for code

**Pull request merged**
